version: 2.1

orbs:
  cypress: cypress-io/cypress@1.3.0
workflows:
  build:
    jobs:
      - cypress/run:
          executor: cypress/browsers-chrome77
          browser: chrome
          start: 'yarn start' # start server before running tests 